spring:
  application:
    name: ludotheque

  data:
    mongodb:
      uri: mongodb://localhost:27017/ludotheque
      database: ludotheque

  # Active le log des requÃªtes Mongo dans la console (utile pour le debug)
  mongodb:
    logging:
      level:
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG
